#!/usr/bin/env python3
# Aggregate an ims-ma3 census and state its error band.
#
# ☠️ THE GATE IS PER LEG, AND ITS SCALE IS THE LEG'S OWN SLEEP - NOT THE ALARM.
# The accumulator wraps at ACCUM_CNT = 255 at ~3.35-3.4 samples/s, so a sample
# whose cnt implies a window longer than the leg actually slept began BEFORE the
# sleep and carries the previous wake's awake current, always upward. On a leg
# that sleeps the full alarm the two scales coincide; on a leg that does not
# sleep - which is exactly what the expensive state does - they differ by 4x, and
# reading the gate as "3.35 x alarm" silently keeps 39 contaminated samples
# instead of 7 and pulls that leg from 91.0 mA down to 84.2 mA. Measured on the
# 2026-09-02 census while trying to reproduce its own published table.
#
# ☠️ AND AGGREGATE sum(accum)/sum(cnt), NOT a mean of per-sample means: each
# sample is an integral over a different number of ticks, so a plain mean weights
# a short window like a long one.
#
# usage: ma3-fit.py <capture-dir> [leg ...]
import sys, re, statistics as st, random, datetime as dt, pathlib

I_RAW_TO_UA = 152588 / 1000          # per the QG datasheet units, /1000 -> uA
SAMPLES_PER_S = 3.35                 # measured: 140 samples over 41 s of sleep

def load(d, leg):
    out = []
    for line in open(d / f'samples-{leg}.txt'):
        m = re.search(r't=(\S+ \S+) acc=0x([0-9a-f]+) cnt=0x([0-9a-f]+)', line)
        if not m:
            continue
        t = dt.datetime.strptime(m.group(1), '%Y-%m-%d %H:%M:%S')
        v = int(m.group(2), 16)
        if v >= 1 << 23:             # 24-bit signed, little endian
            v -= 1 << 24
        out.append((t, v, int(m.group(3), 16)))
    return out

def ma(kept):
    return sum(v for v, c in kept) * I_RAW_TO_UA / sum(c for v, c in kept) / 1000

# ☠️ NO BOOTSTRAP AT SMALL n. Resampling 7 values estimates its own tail: the
# extremes are under-represented and the interval's coverage is known to be poor,
# so it reports a precision it does not have (the first version printed +-8.4 mA
# off 7 samples and looked as authoritative as the +-1.0 off 22). Below MIN_BOOT
# use a t interval, and say n out loud so the reader discounts it.
MIN_BOOT = 15
T975 = {2: 12.706, 3: 4.303, 4: 3.182, 5: 2.776, 6: 2.571, 7: 2.447, 8: 2.365,
        9: 2.306, 10: 2.262, 11: 2.228, 12: 2.201, 13: 2.179, 14: 2.160}

def leg_stats(rows, boots=4000):
    gaps = [(rows[i + 1][0] - rows[i][0]).total_seconds() for i in range(len(rows) - 1)]
    med = st.median(gaps)
    thr = SAMPLES_PER_S * med
    kept = [(v, c) for _, v, c in rows if c < thr]
    if not kept:
        return None
    point = ma(kept)
    n = len(kept)
    if n >= MIN_BOOT:
        bs = sorted(ma([random.choice(kept) for _ in kept]) for _ in range(boots))
        lo, hi = bs[int(0.025 * boots)], bs[int(0.975 * boots) - 1]
        how = 'bootstrap'
    elif n >= 3:
        # ☠️ The point estimate stays sum/sum (each window covers a different
        # number of ticks); the t interval is on the per-sample values, so the two
        # are not the same statistic. That is deliberate: the alternative is a
        # bootstrap that under-reports at this n. Read the interval as the spread,
        # not as a confidence band around exactly this point.
        per = [v * I_RAW_TO_UA / c / 1000 for v, c in kept]
        half = T975.get(n - 1, 2.145) * st.stdev(per) / n ** 0.5
        lo, hi, how = point - half, point + half, f't, df={n - 1}'
    else:
        per = [v * I_RAW_TO_UA / c / 1000 for v, c in kept]
        lo, hi, how = min(per), max(per), 'range only'
    return dict(med=med, thr=thr, kept=n, n=len(rows), ma=point, lo=lo, hi=hi, how=how)

# ☠️ THE TABLE IN THE REPORT IS GENERATED BY THIS, NOT RETYPED. Copying numbers
# by hand is how a published table drifts from the data it claims to summarise -
# and this file exists because reproducing one such table took a sixth review
# round to explain. `--md` prints the markdown rows; paste those, nothing else.
MD = '--md' in sys.argv
argv = [a for a in sys.argv if a != '--md']
d = pathlib.Path(argv[1])
d = d / 'raw' if (d / 'raw').is_dir() else d
legs = argv[2:] or [p.name[8:-4] for p in sorted(d.glob('samples-*.txt'))]
if MD:
    print('| leg | slept | kept | **current** | 95 % CI (within-leg only) |')
    print('|---|---:|---:|---:|---|')
else:
    print(f"{'leg':<4} {'sleep':>7} {'gate':>7} {'kept':>8} {'current':>10}   95% CI (within-leg only)")
for leg in legs:
    r = leg_stats(load(d, leg))
    if not r:
        print(f'{leg:<4} no sample survives the gate')
        continue
    if MD:
        print(f"| {leg} | {r['med']:.0f} s | {r['kept']}/{r['n']} | {r['ma']:.1f} mA | "
              f"±{(r['hi']-r['lo'])/2:.1f} ({r['how']}) |")
        continue
    print(f"{leg:<4} {r['med']:>6.0f}s {r['thr']:>7.0f} {r['kept']:>4}/{r['n']:<3} "
          f"{r['ma']:>8.1f} mA   [{r['lo']:.1f}, {r['hi']:.1f}]  +-{(r['hi']-r['lo'])/2:.1f}  ({r['how']})")
if MD:
    sys.exit(0)
print()
print('☠️ THE CI IS WITHIN-LEG ONLY - the sampling noise of one leg of one boot.')
print('   It says nothing about the PMI632 offset the whole project shares, and')
print('   nothing about the DOMINANT unknown, which is boot-to-boot variation: no')
print('   single leg can see that, however many windows it holds. Label every')
print('   number from here "+-X (within-leg; boot-to-boot unknown)", and once')
print('   several boots exist take the boot-to-boot spread from the SPREAD OF THE')
print('   LEG MEANS - never from the pooled windows, which would hide it.')
